gitfileviewerurl:
    https://github.com/openvswitch/ovs/blob/master/
gitrawfileviewerurl:
    https://raw.githubusercontent.com/openvswitch/ovs/master/
gitdirviewerurl:
    https://github.com/openvswitch/ovs/tree/master/
ovsurl:
    https://www.openvswitch.org
url:
    https://www.openvswitch.org
gems:
    - jekyll-redirect-from
